services:
  - type: web
    name: solenz-uygulama
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: AI_API_KEY
        sync: false # Render dashboard üzerinden manuel eklenmeli
